/*********************************************************************
** Author: Kuljot Biring
**
** Date: June 2, 2018
**
** Challenge: The East Coast sales division of a company generates 58
** percent of total sales. Based on that percentage, write a program
** that will predict how much the East Coast division will generate
** if the company has $8.6 million in sales this year. Display the
** result on the screen.
*********************************************************************/
#include <iostream>


int main()
{
    double eastCoast = .58,
        totalSales = 8600000;

    int easternSales = totalSales * eastCoast;

    std::cout << "The sales generated by the East Coast are " << easternSales << std::endl;
    return 0;
}
